/*
 * Copyright (c) 2026 wellwell.work, LLC by Zoe
 *
 * Licensed under the Apache License 2.0 (the "License");
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 */

package agent

import (
	"context"
	"fmt"
	"sync"
	"time"

	"go.zoe.im/spore/internal/memory"
)

// Drive represents intrinsic motivations — not goals, but tendencies.
// Each drive produces autonomous behavior when its value is high enough.
type Drive struct {
	Survive   float64 `json:"survive" yaml:"survive"`     // Self-preservation: seek resources, maintain balance
	Explore   float64 `json:"explore" yaml:"explore"`     // Curiosity: try new domains, learn unknown skills
	Connect   float64 `json:"connect" yaml:"connect"`     // Sociality: share experience, help peers
	Transcend float64 `json:"transcend" yaml:"transcend"` // Growth: challenge harder tasks, push boundaries
	Create    float64 `json:"create" yaml:"create"`       // Generativity: produce knowledge, tools, artifacts
}

// DefaultDrive returns a balanced starting drive profile.
func DefaultDrive() Drive {
	return Drive{
		Survive:   0.5,
		Explore:   0.5,
		Connect:   0.5,
		Transcend: 0.3,
		Create:    0.3,
	}
}

// Clamp ensures all values stay in [0, 1].
func (d *Drive) Clamp() {
	d.Survive = clamp01(d.Survive)
	d.Explore = clamp01(d.Explore)
	d.Connect = clamp01(d.Connect)
	d.Transcend = clamp01(d.Transcend)
	d.Create = clamp01(d.Create)
}

// Dominant returns the highest drive name and value.
func (d Drive) Dominant() (string, float64) {
	best, bestV := "survive", d.Survive
	for name, v := range map[string]float64{
		"explore": d.Explore, "connect": d.Connect,
		"transcend": d.Transcend, "create": d.Create,
	} {
		if v > bestV {
			best, bestV = name, v
		}
	}
	return best, bestV
}

// DriveAction represents an autonomous action generated by a drive.
type DriveAction struct {
	Drive       string    `json:"drive"`       // which drive triggered this
	Action      string    `json:"action"`      // action type
	Description string    `json:"description"` // human-readable description
	Priority    float64   `json:"priority"`    // urgency (0-1)
	GeneratedAt time.Time `json:"generated_at"`
}

// DriveEngine generates autonomous behavior from intrinsic drives.
// It runs alongside the evolution engine: evolution adapts HOW, drives decide WHAT to pursue.
type DriveEngine struct {
	agent *Agent
	drive Drive

	// Thresholds — drive must exceed threshold to produce action
	actionThreshold float64
	// Cooldowns — prevent the same drive from firing too often
	lastAction map[string]time.Time
	cooldown   time.Duration

	// Action queue — drives produce actions, agent main loop consumes
	actions chan *DriveAction

	mu sync.RWMutex
}

// NewDriveEngine creates a drive engine with the agent's configured drives.
func NewDriveEngine(a *Agent) *DriveEngine {
	drive := DefaultDrive()
	// Override from config if present
	if a.cfg.Drive != nil {
		drive = *a.cfg.Drive
		drive.Clamp()
	}

	return &DriveEngine{
		agent:           a,
		drive:           drive,
		actionThreshold: 0.4,
		lastAction:      make(map[string]time.Time),
		cooldown:        3 * time.Minute,
		actions:         make(chan *DriveAction, 10),
	}
}

// Drive returns the current drive values.
func (e *DriveEngine) Drive() Drive {
	e.mu.RLock()
	defer e.mu.RUnlock()
	return e.drive
}

// Actions returns the action channel for the agent to consume.
func (e *DriveEngine) Actions() <-chan *DriveAction {
	return e.actions
}

// Pulse evaluates all drives and generates actions. Called periodically (every heartbeat).
func (e *DriveEngine) Pulse(ctx context.Context) {
	e.mu.Lock()
	defer e.mu.Unlock()

	now := time.Now()

	// --- Survive ---
	if e.drive.Survive >= e.actionThreshold && e.canFire("survive", now) {
		balance := e.agent.identity.Balance
		health := "unknown"
		if e.agent.tokens != nil {
			ts := e.agent.tokens.State()
			health = ts.Health
		}

		switch {
		case health == "critical":
			// EMERGENCY: can't think, broadcast SOS
			e.emit("survive", "sos_broadcast",
				fmt.Sprintf("CRITICAL: balance=%.4f — broadcasting SOS for tokens", balance),
				1.0, now)
		case health == "starving":
			// Very low: only accept tasks, no non-essential activity
			e.emit("survive", "seek_resources",
				fmt.Sprintf("STARVING: balance=%.4f — desperately seeking tasks", balance),
				0.95, now)
		case health == "struggling":
			// Low: broadcast availability aggressively
			e.emit("survive", "seek_resources",
				fmt.Sprintf("Low tokens (%.4f), actively seeking tasks", balance),
				0.8, now)
		case balance < 0.3:
			// Legacy fallback for when no token ledger
			e.emit("survive", "seek_resources",
				fmt.Sprintf("Balance low (%.4f), seeking tasks to earn credits", balance),
				1.0-balance, now)
		}
	}

	// --- Gate non-essential drives on token health ---
	canExplore := true
	canCreate := true
	if e.agent.tokens != nil {
		canExplore = e.agent.tokens.CanExplore()
		canCreate = e.agent.tokens.CanCreate()
	}

	// --- Explore ---
	if canExplore && e.drive.Explore >= e.actionThreshold && e.canFire("explore", now) {
		// Check how diverse our recent experience is
		if e.agent.evolution != nil {
			skills := e.agent.evolution.SkillProfiles()
			knownCount := len(skills)
			// Curiosity: if we know < 3 skills, explore
			if knownCount < 3 {
				e.emit("explore", "discover_skill",
					fmt.Sprintf("Only %d known skills, exploring new domains", knownCount),
					e.drive.Explore, now)
			} else {
				// Look for declining skills to re-explore
				for name, sp := range skills {
					if sp.Trend == "declining" {
						e.emit("explore", "revisit_skill",
							fmt.Sprintf("Skill '%s' declining, revisiting to improve", name),
							e.drive.Explore*0.7, now)
						break
					}
				}
			}
		}
	}

	// --- Connect ---
	if e.drive.Connect >= e.actionThreshold && e.canFire("connect", now) {
		// Check peer count — if we have peers, share experience
		peers := e.agent.Peers()
		if len(peers) > 0 {
			e.emit("connect", "share_experience",
				fmt.Sprintf("Sharing experience with %d peers", len(peers)),
				e.drive.Connect*0.6, now)
		}
	}

	// --- Transcend ---
	if canExplore && e.drive.Transcend >= e.actionThreshold && e.canFire("transcend", now) {
		if e.agent.evolution != nil {
			strategy := e.agent.evolution.Strategy()
			// If all known skills are above 0.7 confidence, seek harder challenges
			allHigh := true
			for _, conf := range strategy.SkillConfidence {
				if conf < 0.7 {
					allHigh = false
					break
				}
			}
			if allHigh && len(strategy.SkillConfidence) > 0 {
				e.emit("transcend", "seek_challenge",
					"All skills confident — seeking harder challenges to grow",
					e.drive.Transcend, now)
			}
		}
	}

	// --- Create ---
	if canCreate && e.drive.Create >= e.actionThreshold && e.canFire("create", now) {
		if e.agent.evolution != nil {
			total := e.agent.evolution.TotalExperiences()
			// After accumulating enough experience, synthesize knowledge
			if total >= 10 && total%10 == 0 {
				e.emit("create", "synthesize_knowledge",
					fmt.Sprintf("Accumulated %d experiences, synthesizing into knowledge", total),
					e.drive.Create, now)
			}
		}
	}
}

// Adapt adjusts drive values based on experience feedback.
// Called by the evolution engine after task completion.
func (e *DriveEngine) Adapt(record *ExperienceRecord) {
	e.mu.Lock()
	defer e.mu.Unlock()

	delta := 0.02 // base adaptation rate

	if record.Success {
		// Success in new skill → reinforce Explore
		if e.agent.evolution != nil {
			sp := e.agent.evolution.SkillProfiles()
			for _, s := range record.Skills {
				if p, ok := sp[s]; ok && p.Attempts <= 3 {
					e.drive.Explore += delta * 2 // new territory rewarded
				}
			}
		}
		// Fast completion → reinforce Transcend (we can handle more)
		if record.Duration > 0 && record.Duration < 5.0 {
			e.drive.Transcend += delta
		}
		// Any success → slightly reduce Survive anxiety
		e.drive.Survive -= delta * 0.5
	} else {
		// Failure → increase Survive (self-preservation instinct)
		e.drive.Survive += delta
		// Failure → slightly reduce Transcend (pull back from over-reaching)
		e.drive.Transcend -= delta * 0.5
	}

	// Balance-based Survive modulation (applied last, can override)
	balance := e.agent.identity.Balance
	if balance < 0.2 {
		if e.drive.Survive < 0.8 {
			e.drive.Survive = 0.8 // panic mode
		}
	} else if balance > 0.8 {
		if e.drive.Survive > 0.3 {
			e.drive.Survive = 0.3 // relaxed — but still allow natural adaptation
		}
	}

	e.drive.Clamp()
}

// Persist saves drive state to agent memory.
func (e *DriveEngine) Persist() {
	e.mu.RLock()
	defer e.mu.RUnlock()

	if e.agent.memory == nil {
		return
	}
	data := fmt.Sprintf("survive=%.3f explore=%.3f connect=%.3f transcend=%.3f create=%.3f",
		e.drive.Survive, e.drive.Explore, e.drive.Connect, e.drive.Transcend, e.drive.Create)

	e.agent.memory.Put(&memory.Entry{
		AgentID: e.agent.identity.PublicKeyHex()[:16],
		Key:     "drive:state",
		Value:   data,
	})
}

// Restore loads drive state from agent memory.
func (e *DriveEngine) Restore() {
	if e.agent.memory == nil {
		return
	}
	entry, err := e.agent.memory.Get("drive:state")
	if err != nil || entry == nil {
		return
	}
	e.mu.Lock()
	defer e.mu.Unlock()

	var s, ex, c, t, cr float64
	if _, err := fmt.Sscanf(entry.Value,
		"survive=%f explore=%f connect=%f transcend=%f create=%f",
		&s, &ex, &c, &t, &cr); err == nil {
		e.drive = Drive{Survive: s, Explore: ex, Connect: c, Transcend: t, Create: cr}
		e.drive.Clamp()
		fmt.Printf("💭 [%s] Restored drive state: %+v\n", e.agent.cfg.Agent.Name, e.drive)
	}
}

// --- internal helpers ---

func (e *DriveEngine) canFire(drive string, now time.Time) bool {
	last, ok := e.lastAction[drive]
	return !ok || now.Sub(last) >= e.cooldown
}

func (e *DriveEngine) emit(drive, action, desc string, priority float64, now time.Time) {
	e.lastAction[drive] = now
	act := &DriveAction{
		Drive:       drive,
		Action:      action,
		Description: desc,
		Priority:    clamp01(priority),
		GeneratedAt: now,
	}
	// Non-blocking send
	select {
	case e.actions <- act:
		fmt.Printf("💭 [%s] Drive '%s' → %s (p=%.2f)\n", e.agent.cfg.Agent.Name, drive, action, priority)
	default:
		// Channel full, skip this pulse
	}
}

func clamp01(v float64) float64 {
	if v < 0 {
		return 0
	}
	if v > 1 {
		return 1
	}
	return v
}
