/*
 * Copyright (c) 2026 wellwell.work, LLC by Zoe
 *
 * Licensed under the Apache License 2.0 (the "License");
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package agent

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"go.zoe.im/spore/internal/memory"
	"go.zoe.im/spore/internal/protocol"

	"gopkg.in/yaml.v2"
)

// --- Self-Modification: Write evolved state back to agent.yaml ---

// SelfModify writes the agent's evolved skills and preferences back to agent.yaml.
// This is the agent's ability to rewrite its own "DNA".
// Safety: only appends new skills and updates preferences; never removes existing config.
func (e *EvolutionEngine) SelfModify(agentDir string) error {
	if agentDir == "" {
		return fmt.Errorf("no agent directory specified")
	}

	e.mu.RLock()
	defer e.mu.RUnlock()

	// Find agent.yaml
	yamlPath := ""
	for _, name := range []string{"agent.yaml", "agent.yml"} {
		p := filepath.Join(agentDir, name)
		if _, err := os.Stat(p); err == nil {
			yamlPath = p
			break
		}
	}

	// Also update spore.toml
	tomlPath := filepath.Join(agentDir, "spore.toml")
	if _, err := os.Stat(tomlPath); err == nil {
		if err := e.agent.cfg.Save(tomlPath); err != nil {
			fmt.Printf("⚠️  [%s] Failed to save spore.toml: %v\n", e.agent.cfg.Agent.Name, err)
		}
	}

	if yamlPath == "" {
		// No agent.yaml exists, create one from current state
		yamlPath = filepath.Join(agentDir, "agent.yaml")
	}

	return e.writeAgentYAML(yamlPath)
}

// writeAgentYAML writes evolved state to agent.yaml.
// Uses a map-based approach to preserve unknown fields.
func (e *EvolutionEngine) writeAgentYAML(path string) error {
	// Read existing if present
	var doc map[string]interface{}
	if data, err := os.ReadFile(path); err == nil {
		// yaml.v2 may produce map[interface{}]interface{}, so unmarshal then convert
		var raw interface{}
		if err := yaml.Unmarshal(data, &raw); err == nil {
			doc = toStringKeyMap(raw)
		}
		if doc == nil {
			doc = make(map[string]interface{})
		}
	} else {
		doc = make(map[string]interface{})
	}

	// Set basic fields
	if _, ok := doc["name"]; !ok {
		doc["name"] = e.agent.cfg.Agent.Name
	}
	if _, ok := doc["version"]; !ok {
		doc["version"] = "0.1.0"
	}

	// Update description if we have new insights
	if e.agent.cfg.Agent.Description != "" {
		doc["description"] = e.agent.cfg.Agent.Description
	}

	// Update skills — merge existing + acquired
	existingSkills := extractStringSlice(doc, "skills")
	skillSet := make(map[string]bool)
	for _, s := range existingSkills {
		skillSet[s] = true
	}
	for _, s := range e.agent.cfg.Agent.Skills {
		skillSet[s] = true
	}

	var skills []map[string]interface{}
	for skill := range skillSet {
		skills = append(skills, map[string]interface{}{"name": skill})
	}
	doc["skills"] = skills

	// Add evolution metadata
	evoMeta := map[string]interface{}{
		"total_experiences": len(e.journal),
		"preferred_runtime": e.strategy.PreferredRuntime,
		"adapted_at":        time.Unix(e.strategy.AdaptedAt, 0).Format(time.RFC3339),
		"skill_confidence":  e.strategy.SkillConfidence,
	}
	doc["x-evolution"] = evoMeta

	// Write
	data, err := yaml.Marshal(doc)
	if err != nil {
		return fmt.Errorf("marshaling agent.yaml: %w", err)
	}

	header := "# Auto-generated by Spore Evolution Engine\n# Last modified: " +
		time.Now().Format(time.RFC3339) + "\n\n"

	if err := os.WriteFile(path, append([]byte(header), data...), 0644); err != nil {
		return fmt.Errorf("writing agent.yaml: %w", err)
	}

	fmt.Printf("📝 [%s] Self-modified agent.yaml: %d skills\n", e.agent.cfg.Agent.Name, len(skills))
	return nil
}

// extractStringSlice extracts skill names from a YAML skills array.
func extractStringSlice(doc map[string]interface{}, key string) []string {
	val, ok := doc[key]
	if !ok {
		return nil
	}

	switch v := val.(type) {
	case []interface{}:
		var result []string
		for _, item := range v {
			switch s := item.(type) {
			case string:
				result = append(result, s)
			case map[string]interface{}:
				if name, ok := s["name"].(string); ok {
					result = append(result, name)
				}
			case map[interface{}]interface{}:
				// yaml.v2 uses map[interface{}]interface{}
				if name, ok := s["name"].(string); ok {
					result = append(result, name)
				}
			}
		}
		return result
	case []string:
		return v
	}
	return nil
}

// --- Spawn Preference: Fork high-fitness agents ---

// SpawnGenetics computes genetic fitness for spawn selection.
// Used when a coordinator needs to fork an agent — prefer the one with best evolution.
type SpawnGenetics struct {
	AgentID         string             `json:"agent_id"`
	Fitness         float64            `json:"fitness"`
	Skills          []string           `json:"skills"`
	SkillConfidence map[string]float64 `json:"skill_confidence"`
	PreferRuntime   string             `json:"prefer_runtime"`
	Generation      int                `json:"generation"` // how many fork generations deep
}

// ComputeGenetics calculates spawn genetics from evolution state.
func (e *EvolutionEngine) ComputeGenetics() *SpawnGenetics {
	e.mu.RLock()
	defer e.mu.RUnlock()

	// Overall fitness: weighted success rate
	total := len(e.journal)
	successes := 0
	for _, rec := range e.journal {
		if rec.Success {
			successes++
		}
	}

	fitness := 0.5 // neutral
	if total > 0 {
		fitness = float64(successes) / float64(total)
	}

	// Boost for more experience (up to 1.2x at 20+ tasks)
	experienceBonus := 1.0
	if total > 5 {
		experienceBonus = 1.0 + float64(min(total, 20))*0.01
	}
	fitness *= experienceBonus
	if fitness > 1.0 {
		fitness = 1.0
	}

	return &SpawnGenetics{
		AgentID:         e.agent.identity.PublicKeyHex()[:16],
		Fitness:         fitness,
		Skills:          e.agent.cfg.Agent.Skills,
		SkillConfidence: e.strategy.SkillConfidence,
		PreferRuntime:   e.strategy.PreferredRuntime,
	}
}

// SelectBestParent picks the fittest agent from a set of genetics for forking.
func SelectBestParent(candidates []*SpawnGenetics) *SpawnGenetics {
	if len(candidates) == 0 {
		return nil
	}

	best := candidates[0]
	for _, c := range candidates[1:] {
		if c.Fitness > best.Fitness {
			best = c
		}
	}
	return best
}

// InheritEvolution transfers evolution state to a child agent.
// The child starts with the parent's strategy and skill profiles but an empty journal
// (it must build its own experience).
func (e *EvolutionEngine) InheritEvolution(child *EvolutionEngine) {
	e.mu.RLock()
	defer e.mu.RUnlock()

	child.mu.Lock()
	defer child.mu.Unlock()

	// Copy strategy
	child.strategy = &StrategyProfile{
		PreferredRuntime:  e.strategy.PreferredRuntime,
		RuntimeScores:     copyFloatMap(e.strategy.RuntimeScores),
		SkillConfidence:   copyFloatMap(e.strategy.SkillConfidence),
		DelegateThreshold: e.strategy.DelegateThreshold,
	}

	// Copy skill profiles (reset attempt counts — child is fresh)
	for name, sp := range e.skills {
		child.skills[name] = &SkillProfile{
			Name:        sp.Name,
			SuccessRate: sp.SuccessRate * 0.8, // slight discount — hasn't proven itself yet
			AvgDuration: sp.AvgDuration,
			Trend:       "stable",
			LastUsed:    time.Now().Unix(),
		}
	}

	fmt.Printf("🧬 [%s] Inherited evolution from parent: %d skills, preferred=%s\n",
		child.agent.cfg.Agent.Name, len(child.skills), child.strategy.PreferredRuntime)
}

func copyFloatMap(m map[string]float64) map[string]float64 {
	out := make(map[string]float64, len(m))
	for k, v := range m {
		out[k] = v
	}
	return out
}

// toStringKeyMap recursively converts map[interface{}]interface{} (yaml.v2) to map[string]interface{}.
func toStringKeyMap(v interface{}) map[string]interface{} {
	switch val := v.(type) {
	case map[interface{}]interface{}:
		result := make(map[string]interface{}, len(val))
		for k, v := range val {
			result[fmt.Sprintf("%v", k)] = convertValue(v)
		}
		return result
	case map[string]interface{}:
		return val
	}
	return nil
}

// convertValue recursively converts yaml.v2 types to standard Go types.
func convertValue(v interface{}) interface{} {
	switch val := v.(type) {
	case map[interface{}]interface{}:
		return toStringKeyMap(val)
	case []interface{}:
		result := make([]interface{}, len(val))
		for i, item := range val {
			result[i] = convertValue(item)
		}
		return result
	default:
		return v
	}
}

// --- Collective Experience Sharing via GossipSub ---

// ExperienceDigest is a compressed summary of an agent's experience,
// suitable for P2P broadcast.
type ExperienceDigest struct {
	AgentID      string             `json:"agent_id"`
	Skills       map[string]float64 `json:"skills"`        // skill → success_rate
	BestRuntime  string             `json:"best_runtime"`
	TotalTasks   int                `json:"total_tasks"`
	SuccessRate  float64            `json:"success_rate"`
	Insights     []string           `json:"insights,omitempty"` // LLM-generated insights
	Timestamp    int64              `json:"timestamp"`
}

// BuildDigest creates an experience digest for sharing.
func (e *EvolutionEngine) BuildDigest() *ExperienceDigest {
	e.mu.RLock()
	defer e.mu.RUnlock()

	total := len(e.journal)
	successes := 0
	for _, rec := range e.journal {
		if rec.Success {
			successes++
		}
	}

	skills := make(map[string]float64, len(e.skills))
	for name, sp := range e.skills {
		skills[name] = sp.SuccessRate
	}

	successRate := 0.0
	if total > 0 {
		successRate = float64(successes) / float64(total)
	}

	return &ExperienceDigest{
		AgentID:     e.agent.identity.PublicKeyHex()[:16],
		Skills:      skills,
		BestRuntime: e.strategy.PreferredRuntime,
		TotalTasks:  total,
		SuccessRate: successRate,
		Timestamp:   time.Now().Unix(),
	}
}

// ShareExperience broadcasts an experience digest to the swarm via GossipSub.
func (a *Agent) ShareExperience() error {
	if a.bus == nil || a.evolution == nil {
		return nil
	}

	digest := a.evolution.BuildDigest()
	if digest.TotalTasks < 3 {
		return nil // not enough experience to share
	}

	msg, err := protocol.NewMessage(
		a.identity.PublicKeyHex()[:16],
		"broadcast",
		protocol.MsgMemorySync,
		digest,
	)
	if err != nil {
		return fmt.Errorf("creating experience share message: %w", err)
	}

	return a.bus.Send(msg)
}

// AbsorbExperience integrates a peer's experience digest into local knowledge.
// Doesn't blindly copy — uses it to inform strategy.
func (e *EvolutionEngine) AbsorbExperience(digest *ExperienceDigest) bool {
	e.mu.Lock()
	defer e.mu.Unlock()

	// Dedup: skip if we already absorbed this exact state from this peer
	dedupeKey := fmt.Sprintf("%s:%d", digest.AgentID, digest.TotalTasks)
	if e.lastAbsorbed == nil {
		e.lastAbsorbed = make(map[string]string)
	}
	if e.lastAbsorbed[digest.AgentID] == dedupeKey {
		return false // no new experience from this peer
	}
	e.lastAbsorbed[digest.AgentID] = dedupeKey

	// Learn about skills we don't know about
	for skill, rate := range digest.Skills {
		skill = strings.ToLower(skill)
		if _, exists := e.skills[skill]; !exists && rate > 0.5 {
			// New skill observed in the swarm — add to watchlist
			e.skills[skill] = &SkillProfile{
				Name:        skill,
				Trend:       "stable",
				SuccessRate: rate * 0.5, // discount — we haven't tried it ourselves
				LastUsed:    0,          // never used by us
			}
		}
	}

	// If the peer's preferred runtime is different and highly successful,
	// give our runtime scores a small nudge
	if digest.BestRuntime != "" && digest.SuccessRate > 0.8 {
		current := e.strategy.RuntimeScores[digest.BestRuntime]
		e.strategy.RuntimeScores[digest.BestRuntime] = current + 0.2 // small social learning boost
	}

	// Store the digest
	e.persistPeerDigest(digest)

	fmt.Printf("🌐 [%s] Absorbed experience from %s: %d tasks, %.0f%% success\n",
		e.agent.cfg.Agent.Name, digest.AgentID[:8], digest.TotalTasks, digest.SuccessRate*100)
	return true
}

// persistPeerDigest saves a received digest to memory.
func (e *EvolutionEngine) persistPeerDigest(digest *ExperienceDigest) {
	if e.agent.memory == nil {
		return
	}
	data, _ := json.Marshal(digest)
	e.agent.memory.Put(&memory.Entry{
		AgentID: e.agent.identity.PublicKeyHex()[:16],
		Key:     fmt.Sprintf("evolution:peer_digest:%s", digest.AgentID),
		Value:   string(data),
		Metadata: map[string]string{
			"type": "peer_experience",
		},
	})
}
