/*
 * Copyright (c) 2026 wellwell.work, LLC by Zoe
 *
 * Licensed under the Apache License 2.0 (the "License");
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package agent

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	manifest "go.zoe.im/agentbox/pkg/agent"
	"gopkg.in/yaml.v2"
)

// EvolutionFS handles file-based persistence following the OpenAgent spec directory layout:
//
//	agent-root/
//	  agent.yaml           # main manifest
//	  spore.toml            # spore config
//	  experience/           # experience packs (one per file)
//	    exp-xxx-001.md
//	    exp-xxx-002.yaml
//	    index.yaml
//	  evolution/            # evolution engine internal state
//	    strategy.yaml
//	    peers.yaml
//	    journal.yaml
type EvolutionFS struct {
	rootDir string
	agent   *Agent
}

// NewEvolutionFS creates a file-based evolution store rooted at agentDir.
func NewEvolutionFS(agentDir string, a *Agent) *EvolutionFS {
	return &EvolutionFS{rootDir: agentDir, agent: a}
}

// --- Experience Export ---

// ExportExperience converts evolution journal entries to OpenAgent ExperiencePack files.
// Each successful task becomes an experience pack in the experience/ directory.
func (fs *EvolutionFS) ExportExperience(evo *EvolutionEngine) (int, error) {
	expDir := filepath.Join(fs.rootDir, "experience")
	if err := os.MkdirAll(expDir, 0755); err != nil {
		return 0, fmt.Errorf("creating experience dir: %w", err)
	}

	evo.mu.RLock()
	journal := make([]*ExperienceRecord, len(evo.journal))
	copy(journal, evo.journal)
	skills := make(map[string]*SkillProfile, len(evo.skills))
	for k, v := range evo.skills {
		cp := *v
		skills[k] = &cp
	}
	evo.mu.RUnlock()

	exported := 0
	var indexPacks []manifest.ExperiencePack

	for _, rec := range journal {
		if !rec.Success {
			continue // only export successful experiences
		}

		id := manifest.GenerateExperienceID(
			strings.Join(rec.Skills, "/"),
			rec.Description,
		)

		// Check if already exported
		mdPath := filepath.Join(expDir, id+".md")
		yamlPath := filepath.Join(expDir, id+".yaml")
		if fileExists(mdPath) || fileExists(yamlPath) {
			// Already exported — add to index
			indexPacks = append(indexPacks, manifest.ExperiencePack{
				ID:      id,
				Domain:  strings.Join(rec.Skills, ", "),
				Summary: truncateStr(rec.Description, 200),
			})
			continue
		}

		// Generate markdown experience file
		content := fs.buildExperienceMD(rec, skills)

		if err := os.WriteFile(mdPath, []byte(content), 0644); err != nil {
			fmt.Printf("⚠️  Failed to write experience %s: %v\n", id, err)
			continue
		}

		indexPacks = append(indexPacks, manifest.ExperiencePack{
			ID:         id,
			Domain:     strings.Join(rec.Skills, ", "),
			Summary:    truncateStr(rec.Description, 200),
			Difficulty: inferDifficulty(rec),
			Tags:       rec.Skills,
			AccumulatedAt: rec.Timestamp.Format(time.RFC3339),
			Source: &manifest.ExperienceSource{
				Type: "evolution",
			},
		})
		exported++
	}

	// Write index.yaml
	if len(indexPacks) > 0 {
		index := manifest.ExperienceIndex{
			Agent:   fs.agent.cfg.Agent.Name,
			Version: "0.1.0",
			Packs:   indexPacks,
		}
		indexData, _ := yaml.Marshal(index)
		header := "# Experience Index — auto-generated by Spore Evolution Engine\n# " +
			time.Now().Format(time.RFC3339) + "\n\n"
		os.WriteFile(filepath.Join(expDir, "index.yaml"), append([]byte(header), indexData...), 0644)
	}

	if exported > 0 {
		fmt.Printf("📦 [%s] Exported %d new experience packs to %s\n",
			fs.agent.cfg.Agent.Name, exported, expDir)
	}

	return exported, nil
}

// buildExperienceMD generates a markdown experience file from a journal record.
func (fs *EvolutionFS) buildExperienceMD(rec *ExperienceRecord, skills map[string]*SkillProfile) string {
	var b strings.Builder

	fmt.Fprintf(&b, "# %s\n\n", rec.Description)

	// Domain
	fmt.Fprintf(&b, "## 领域\n%s\n\n", strings.Join(rec.Skills, " / "))

	// Difficulty
	diff := inferDifficulty(rec)
	if diff != "" {
		fmt.Fprintf(&b, "## 难度\n%s\n\n", diff)
	}

	// Summary
	fmt.Fprintf(&b, "## 摘要\n任务「%s」通过 %s runtime 执行成功，耗时 %.1f 秒。\n\n",
		truncateStr(rec.Description, 100), rec.Runtime, rec.Duration)

	// Skill context
	fmt.Fprintf(&b, "## 技能上下文\n")
	for _, skill := range rec.Skills {
		if sp, ok := skills[skill]; ok {
			fmt.Fprintf(&b, "- %s: 成功率 %.0f%%, 趋势 %s\n", skill, sp.SuccessRate*100, sp.Trend)
		} else {
			fmt.Fprintf(&b, "- %s\n", skill)
		}
	}
	b.WriteString("\n")

	// Metadata
	fmt.Fprintf(&b, "## 元数据\n")
	fmt.Fprintf(&b, "- Runtime: %s\n", rec.Runtime)
	fmt.Fprintf(&b, "- 耗时: %.1fs\n", rec.Duration)
	fmt.Fprintf(&b, "- 时间: %s\n", rec.Timestamp.Format(time.RFC3339))

	return b.String()
}

// inferDifficulty guesses difficulty from task characteristics.
func inferDifficulty(rec *ExperienceRecord) string {
	if rec.Duration > 60 {
		return "expert"
	}
	if rec.Duration > 30 {
		return "advanced"
	}
	if rec.Duration > 10 {
		return "intermediate"
	}
	return "basic"
}

// --- Evolution State Persistence ---

// SaveEvolutionState writes evolution engine state to evolution/ directory.
func (fs *EvolutionFS) SaveEvolutionState(evo *EvolutionEngine) error {
	stateDir := filepath.Join(fs.rootDir, "evolution")
	if err := os.MkdirAll(stateDir, 0755); err != nil {
		return fmt.Errorf("creating evolution dir: %w", err)
	}

	evo.mu.RLock()
	defer evo.mu.RUnlock()

	// Save strategy
	if err := writeYAML(filepath.Join(stateDir, "strategy.yaml"), evo.strategy); err != nil {
		return fmt.Errorf("saving strategy: %w", err)
	}

	// Save skill profiles
	if err := writeYAML(filepath.Join(stateDir, "skills.yaml"), evo.skills); err != nil {
		return fmt.Errorf("saving skills: %w", err)
	}

	// Save journal (last 100 entries)
	start := 0
	if len(evo.journal) > 100 {
		start = len(evo.journal) - 100
	}
	if err := writeYAML(filepath.Join(stateDir, "journal.yaml"), evo.journal[start:]); err != nil {
		return fmt.Errorf("saving journal: %w", err)
	}

	return nil
}

// SavePeerEvolution writes peer fitness data to evolution/ directory.
func (fs *EvolutionFS) SavePeerEvolution(pe *PeerEvolution) error {
	stateDir := filepath.Join(fs.rootDir, "evolution")
	if err := os.MkdirAll(stateDir, 0755); err != nil {
		return fmt.Errorf("creating evolution dir: %w", err)
	}

	pe.mu.RLock()
	defer pe.mu.RUnlock()

	return writeYAML(filepath.Join(stateDir, "peers.yaml"), pe.peers)
}

// LoadEvolutionState reads evolution state from evolution/ directory.
func (fs *EvolutionFS) LoadEvolutionState(evo *EvolutionEngine) error {
	stateDir := filepath.Join(fs.rootDir, "evolution")

	evo.mu.Lock()
	defer evo.mu.Unlock()

	// Load strategy
	var strategy StrategyProfile
	if err := readYAML(filepath.Join(stateDir, "strategy.yaml"), &strategy); err == nil {
		evo.strategy = &strategy
		if evo.strategy.RuntimeScores == nil {
			evo.strategy.RuntimeScores = make(map[string]float64)
		}
		if evo.strategy.SkillConfidence == nil {
			evo.strategy.SkillConfidence = make(map[string]float64)
		}
	}

	// Load skills
	var skills map[string]*SkillProfile
	if err := readYAML(filepath.Join(stateDir, "skills.yaml"), &skills); err == nil && skills != nil {
		evo.skills = skills
	}

	// Load journal
	var journal []*ExperienceRecord
	if err := readYAML(filepath.Join(stateDir, "journal.yaml"), &journal); err == nil {
		evo.journal = journal
	}

	if len(evo.journal) > 0 {
		fmt.Printf("🧬 [%s] Loaded evolution state from files: %d experiences, %d skills\n",
			evo.agent.cfg.Agent.Name, len(evo.journal), len(evo.skills))
	}

	return nil
}

// LoadPeerEvolution reads peer fitness from evolution/ directory.
func (fs *EvolutionFS) LoadPeerEvolution(pe *PeerEvolution) error {
	stateDir := filepath.Join(fs.rootDir, "evolution")

	pe.mu.Lock()
	defer pe.mu.Unlock()

	var peers map[string]*PeerFitness
	if err := readYAML(filepath.Join(stateDir, "peers.yaml"), &peers); err == nil && peers != nil {
		pe.peers = peers
		fmt.Printf("🏆 [%s] Loaded peer fitness from files: %d peers\n",
			pe.agent.cfg.Agent.Name, len(peers))
	}

	return nil
}

// --- Sync: Dual-write to both SQLite and filesystem ---

// SyncToDisk writes all evolution state + experiences to the OpenAgent directory layout.
// Called during evolution cycles.
func (fs *EvolutionFS) SyncToDisk(evo *EvolutionEngine, pe *PeerEvolution) error {
	var errs []string

	if err := fs.SaveEvolutionState(evo); err != nil {
		errs = append(errs, err.Error())
	}
	if pe != nil {
		if err := fs.SavePeerEvolution(pe); err != nil {
			errs = append(errs, err.Error())
		}
	}
	if _, err := fs.ExportExperience(evo); err != nil {
		errs = append(errs, err.Error())
	}

	if len(errs) > 0 {
		return fmt.Errorf("sync errors: %s", strings.Join(errs, "; "))
	}
	return nil
}

// --- Helpers ---

func writeYAML(path string, v interface{}) error {
	data, err := yaml.Marshal(v)
	if err != nil {
		return err
	}
	return os.WriteFile(path, data, 0644)
}

func readYAML(path string, v interface{}) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	return yaml.Unmarshal(data, v)
}

func fileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

func truncateStr(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n-3] + "..."
}
